# =========================================================================
# FH_Carrier PCIe Reference Clock Monitor
# PZ-ZU7EV / XCZU7EV
# =========================================================================

# M2_PCIE_REFCLK_SOM -> GTH Bank 223 MGTREFCLK0
#
# Actual top-level ports generated by the Block Design wrapper.

set_property PACKAGE_PIN AD8 \
    [get_ports {M2_PCIE_REFCLK_SOM_P_0}]

set_property PACKAGE_PIN AD7 \
    [get_ports {M2_PCIE_REFCLK_SOM_N_0}]


# External PCIe reference clock = 100 MHz

create_clock \
    -name M2_PCIE_REFCLK_SOM_100M \
    -period 10.000 \
    [get_ports {M2_PCIE_REFCLK_SOM_P_0}]


# =========================================================================
# Clock-domain relationship
# =========================================================================
#
# clk_pl_0:
#   PS-generated 100 MHz PL clock.
#
# pcie_refclk_odiv2:
#   M2 PCIe reference clock after IBUFDS_GTE4 ODIV2,
#   nominally 50 MHz.
#
# These clocks have no phase/frequency relationship.
# CDC inside fh_pcie_refclk_monitor is handled with Gray coding +
# two-stage ASYNC_REG synchronizers.

set_clock_groups -asynchronous \
    -group [get_clocks {clk_pl_0}] \
    -group [get_clocks {pcie_refclk_odiv2}]
    